spring.application.name=StudentInternshipPortal


# ==========================
# DATABASE CONFIGURATION
# ==========================

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/internship_portal_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ==========================
# JPA CONFIGURATION
# ==========================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=true


# ==========================
# SERVER CONFIGURATION
# ==========================

server.port=${PORT:8080}


# ==========================
# LOGGING
# ==========================

logging.level.org.springframework.security=INFO


# ==========================
# FILE UPLOAD
# ==========================

spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=5MB

spring.servlet.multipart.max-request-size=5MB


# ==========================
# EMAIL CONFIGURATION
# ==========================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# ==========================
# CLOUDINARY
# ==========================

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}


























